/**
 * WK-0160 — real cross-process tunnel integration test.
 *
 * Closes the gap the WK names: `dispatch-v2-tunnel.test.ts` and
 * `dispatch-v2-pipeline-s5.test.ts` only assert generated bash-script TEXT
 * (or, for `buildPiBaseUrl`, a pure string transform) — no existing test
 * starts tunnel.ts's REAL forwarder+relay process pair and sends a real HTTP
 * request through it. This file does exactly that: a local stub
 * `http.Server` stands in for the model backend; the forwarder.js/relay.js
 * scripts are generated by tunnel.ts's own `buildTunnelScripts()` (never
 * hand-written here) and run as real Node child processes; every assertion
 * reads what the stub actually RECEIVED, never the generated script text.
 *
 * Bug classes this closes (S6a):
 *
 *   - `d86240c` (baseUrl path silently stripped): pipeline.ts's
 *     `buildPiBaseUrl` — the actual fix — is already unit-tested directly in
 *     `dispatch-v2-pipeline-s5.test.ts` as a pure string transform. The gap
 *     THIS file closes is the untested REST of the chain: does the
 *     relay/socket/forwarder hop preserve an already-correct path end to end
 *     to the real target? The "request shape" tests below build the
 *     client's request URL by calling the REAL `buildPiBaseUrl` (not a
 *     hand-rewritten equivalent), so a regression in its path-preservation
 *     logic flips this file red too, not only the pipeline-s5 suite.
 *     `buildPiBaseUrl` hardcodes `TUNNEL_RELAY_PORT`; since this file binds
 *     the relay to a dynamically-allocated port instead (see "Port
 *     allocation" below), the fixed-port literal in its return value is
 *     substituted for the real port this harness's relay is actually
 *     listening on — only the port number is swapped, the path-preservation
 *     logic itself runs unmodified.
 *   - `19227fc` (proxy loop on loopback): Pi's own HTTP client honors
 *     `HTTP_PROXY`. When its baseUrl and its `HTTP_PROXY` point at the SAME
 *     loopback relay address, a proxy-aware client sends an absolute-URI
 *     request that names the RELAY's own address as its destination instead
 *     of the real target — confirmed by direct capture while writing this
 *     file (see the "no proxy-loop" describe block): without
 *     `NO_PROXY`/`no_proxy` set, curl's absolute-URI request line embeds the
 *     relay's own loopback address, the forwarder denies it (403, not on the
 *     allowlist) or would otherwise double-hop through the tunnel a second
 *     time. `no_proxy=127.0.0.1,localhost` / `NO_PROXY=127.0.0.1,localhost`
 *     (tunnel.ts's `buildTunnelBashLines`) is the fix — it tells a
 *     proxy-aware client to connect directly (origin-form) instead, which
 *     the forwarder's origin-form branch correctly resolves to the real
 *     target. `dispatch-v2-tunnel.test.ts` never asserts on
 *     `no_proxy`/`NO_PROXY` at all (checked directly: absent from that
 *     file), so this is the FIRST test — at any level — covering this fix.
 *
 * Empirical finding carried forward (also independently re-confirmed while
 * writing this file — see the probe capture referenced in the "no
 * proxy-loop" and "allowlist" describe blocks below): the forwarder's
 * `matchesAllowlist()` matches HOSTNAME ONLY, never the port. A stub bound
 * to the SAME hostname the relay itself uses (127.0.0.1) makes a
 * self-referential proxy-loop request accidentally re-resolve correctly on
 * its own second hop through the tunnel (an allowed-by-hostname false
 * green), masking the exact bug this file exists to catch. Every test below
 * therefore binds the stub to a DISTINCT loopback alias, `127.0.0.2` — still
 * loopback (no real network egress), never the same hostname as the relay's
 * own `127.0.0.1`.
 *
 * Port allocation (CRITICAL — GPT findings 1-2 against the discarded prior
 * attempt): the stub is a real `http.Server` in this process, so it binds
 * port 0 and reads `.address().port` back directly. The relay is a SEPARATE
 * Node child process running tunnel.ts's own generated script text (never
 * hand-written here); that script logs the REQUESTED port argument on its
 * own stdout, not the OS-assigned one (`console.log('...' + PORT + ...)`
 * where `PORT` is the argv value, not `server.address().port`) — changing
 * that would be a production-code edit, out of scope here. So there is no
 * in-band channel for the relay child to self-report an ephemeral bind back
 * to this parent process. `getFreePort()` uses the identical OS primitive
 * (bind a throwaway server to `:0`, read back `.address().port`, close it
 * immediately) and hands that discovered, collision-free number to the
 * relay's argv explicitly — this file never references the fixed
 * `TUNNEL_RELAY_PORT` for a bind, and never uses an incrementing counter.
 *
 * Red-verification (WK-0160 checklist item — performed locally, not
 * committed): confirmed by temporarily materializing
 * `git show 19227fc~1:packages/dispatch-core/src/tunnel.ts` (dropping the
 * `no_proxy`/`NO_PROXY` export lines) and re-running the "no proxy-loop"
 * describe block — the "WITH NO_PROXY" test (which relies on those exact
 * exported lines existing) flipped red, confirming this file would have
 * caught that regression; `packages/dispatch-core/src/tunnel.ts` was then
 * restored via `git checkout --`. For `d86240c`, `dispatch-v2-pipeline-s5.
 * test.ts` was confirmed to already flip red against
 * `git show d86240c~1:packages/dispatch-core/src/pipeline.ts` (that suite
 * was introduced BY that very commit to lock the fix in); additionally,
 * because the "request shape" tests below call the real `buildPiBaseUrl`
 * (see above), materializing that same pre-`d86240c` pipeline.ts also
 * flipped THIS file's path-preservation test red (the import of the
 * now-nonexistent `buildPiBaseUrl` export fails), confirming this file
 * independently guards the same regression, not only via the pre-existing
 * suite. `packages/dispatch-core/src/pipeline.ts` was restored via
 * `git checkout --` afterward in both cases.
 *
 * Out of scope (per the WK): real bwrap sandboxing (WK-0159), real external
 * network egress, real model backend calls, WIN_HOST resolution (feature
 * deleted in the D6 rewrite — `needsWinHostResolution`/`applyWinHost` no
 * longer exist; confirmed absent from pipeline.ts/tunnel.ts by direct
 * search before writing this file).
 */
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { execFileSync, spawn, type ChildProcess } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import {
  createServer as createHttpServer,
  request as httpRequest,
  type IncomingHttpHeaders,
  type IncomingMessage,
  type Server as HttpServer,
  type ServerResponse,
} from 'node:http';
import { createServer as createNetServer, connect as netConnect } from 'node:net';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { buildTunnelBashLines, buildTunnelScripts, TUNNEL_RELAY_PORT, type TunnelConfig } from '../packages/dispatch-core/src/tunnel.js';
import { buildPiBaseUrl, runDispatch } from '../packages/dispatch-core/src/pipeline.js';
import * as spawnIsolatedModule from '../packages/dispatch-core/src/spawn-isolated.js';

function readFixtureFile(name: string): string {
  return readFileSync(join(__dirname, 'fixtures', name), 'utf8');
}

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

async function createTempDir(prefix: string): Promise<string> {
  return mkdtemp(join(tmpdir(), prefix));
}

/** Ask the OS for a free TCP port via a throwaway :0 bind, then release it immediately. See the "Port allocation" header note above for why this is needed for the relay specifically. */
function getFreePort(): Promise<number> {
  return new Promise((resolve, reject) => {
    const probe = createNetServer();
    probe.once('error', reject);
    probe.listen(0, '127.0.0.1', () => {
      const address = probe.address();
      if (!address || typeof address === 'string') {
        probe.close();
        reject(new Error('getFreePort: failed to read back a bound port'));
        return;
      }
      const { port } = address;
      probe.close(() => resolve(port));
    });
  });
}

/** Poll-connect until `target` (a TCP port or a unix socket path) accepts a connection, or time out. */
function waitForListen(target: number | string, timeoutMs = 5000): Promise<void> {
  return new Promise((resolve, reject) => {
    const deadline = Date.now() + timeoutMs;
    const attempt = () => {
      const sock = typeof target === 'number' ? netConnect({ host: '127.0.0.1', port: target }) : netConnect({ path: target });
      sock.once('connect', () => {
        sock.end();
        resolve();
      });
      sock.once('error', () => {
        sock.destroy();
        if (Date.now() > deadline) reject(new Error(`waitForListen: timed out waiting for ${String(target)} to accept connections`));
        else setTimeout(attempt, 25);
      });
    };
    attempt();
  });
}

/**
 * Parse `export KEY=value` lines (tunnel.ts's `buildTunnelBashLines`
 * `preJailLines` shape) into a plain object, unquoting a `shQuote()`-wrapped
 * value when present. Used to derive the REAL proxy env values tunnel.ts
 * generates rather than hand-duplicating a literal in this file -- so a
 * regression that removes/changes those export lines in tunnel.ts flips the
 * "no proxy-loop" tests below red (confirmed empirically: a hand-set literal
 * kept passing even against a tunnel.ts with the no_proxy/NO_PROXY export
 * lines removed -- see the header's red-verification note).
 */
function extractShellExports(lines: string[]): Record<string, string> {
  const result: Record<string, string> = {};
  for (const line of lines) {
    const match = line.match(/^export (\w+)=(.*)$/);
    if (!match) continue;
    let value = match[2];
    if (value.startsWith("'") && value.endsWith("'")) value = value.slice(1, -1).replace(/'\\''/g, "'");
    result[match[1]] = value;
  }
  return result;
}

const PROXY_ENV_VARS = ['HTTP_PROXY', 'http_proxy', 'HTTPS_PROXY', 'https_proxy', 'NO_PROXY', 'no_proxy'] as const;

/**
 * Run curl against `url`, resolving with its numeric HTTP status code.
 *
 * GPT finding 3 (discarded prior attempt): the earlier `curlStatus()` used
 * `Number(stdout) || 0`, silently coercing BOTH a genuine spawn/curl failure
 * AND an empty-stdout edge case to status 0 — indistinguishable from a real
 * "connection refused" 000 and useless for diagnosing a failing test. This
 * version REJECTS instead: a failed spawn, a non-zero curl exit, or
 * unparseable stdout all surface the real stderr text, never a silent 0.
 *
 * Defaults to a proxy-env-scrubbed environment (never inherits an ambient
 * `HTTP_PROXY` etc from the host shell) unless the caller explicitly passes
 * `env` — only the "no proxy-loop" tests below need to, deliberately.
 */
function curlStatus(
  url: string,
  opts: { env?: NodeJS.ProcessEnv; extraArgs?: string[]; timeoutMs?: number } = {},
): Promise<number> {
  return new Promise((resolve, reject) => {
    let env = opts.env;
    if (!env) {
      env = { ...process.env };
      for (const key of PROXY_ENV_VARS) delete env[key];
    }
    const args = [
      '-s',
      '-o',
      '/dev/null',
      '-w',
      '%{http_code}',
      '--max-time',
      String((opts.timeoutMs ?? 5000) / 1000),
      ...(opts.extraArgs ?? []),
      url,
    ];
    const child = spawn('curl', args, { env });
    let stdout = '';
    let stderr = '';
    child.stdout.on('data', (d) => (stdout += d));
    child.stderr.on('data', (d) => (stderr += d));
    child.once('error', (err) => reject(new Error(`curl failed to spawn for ${url}: ${err.message}`)));
    child.once('close', (code) => {
      if (code !== 0) {
        reject(new Error(`curl exited ${code} for ${url}: ${stderr.trim() || '(no stderr)'}`));
        return;
      }
      const status = Number(stdout.trim());
      if (!Number.isInteger(status)) {
        reject(new Error(`curl produced a non-numeric status "${stdout.trim()}" for ${url}: ${stderr.trim() || '(no stderr)'}`));
        return;
      }
      resolve(status);
    });
  });
}

interface ReceivedRequest {
  url?: string;
  method?: string;
  headers: IncomingHttpHeaders;
}

interface TunnelHarness {
  tmpDir: string;
  stub: HttpServer;
  stubHost: string;
  stubPort: number;
  relayPort: number;
  forwarder: ChildProcess;
  relay: ChildProcess;
  config: TunnelConfig;
}

/**
 * Starts a real stub `http.Server` (standing in for the model backend, on
 * the DISTINCT loopback alias `127.0.0.2` — see header note), generates the
 * forwarder+relay scripts via tunnel.ts's own `buildTunnelScripts()`, and
 * starts both as real Node child processes (never hand-written here).
 */
async function startTunnelHarness(opts: {
  requestHandler: (req: IncomingMessage, res: ServerResponse) => void;
  webEnabled?: boolean;
  allowedHosts?: string[];
}): Promise<TunnelHarness> {
  const tmpDir = await createTempDir('tunnel-integration-');
  const stubHost = '127.0.0.2';
  const stub = createHttpServer(opts.requestHandler);
  await new Promise<void>((resolve, reject) => {
    stub.once('error', reject);
    stub.listen(0, stubHost, () => resolve());
  });
  const stubAddress = stub.address();
  if (!stubAddress || typeof stubAddress === 'string') throw new Error('stub server failed to bind');
  const stubPort = stubAddress.port;

  const socketPath = join(tmpDir, 'tunnel.sock');
  const logPath = join(tmpDir, 'tunnel-destinations.log');
  const config: TunnelConfig = {
    socketPath,
    targetUrl: `http://${stubHost}:${stubPort}/v1`,
    allowedHosts: opts.allowedHosts ?? [stubHost],
    webEnabled: opts.webEnabled ?? false,
  };
  const { forwarderScript, relayScript } = buildTunnelScripts(config);
  const forwarderPath = join(tmpDir, 'forwarder.js');
  const relayPath = join(tmpDir, 'relay.js');
  await writeFile(forwarderPath, forwarderScript, 'utf8');
  await writeFile(relayPath, relayScript, 'utf8');

  const forwarder = spawn(
    process.execPath,
    [forwarderPath, socketPath, config.targetUrl, config.webEnabled ? 'true' : 'false', logPath, JSON.stringify(config.allowedHosts)],
    { stdio: ['ignore', 'pipe', 'pipe'] },
  );
  await waitForListen(socketPath);

  const relayPort = await getFreePort();
  const relay = spawn(process.execPath, [relayPath, String(relayPort), socketPath], { stdio: ['ignore', 'pipe', 'pipe'] });
  await waitForListen(relayPort);

  return { tmpDir, stub, stubHost, stubPort, relayPort, forwarder, relay, config };
}

function killAndWait(child: ChildProcess, timeoutMs = 2000): Promise<void> {
  return new Promise((resolve) => {
    if (child.exitCode !== null || child.signalCode !== null) {
      resolve();
      return;
    }
    const timer = setTimeout(() => resolve(), timeoutMs); // best-effort -- never hang a test's cleanup on a stuck child
    child.once('exit', () => {
      clearTimeout(timer);
      resolve();
    });
    child.kill();
  });
}

async function stopTunnelHarness(harness: TunnelHarness): Promise<void> {
  await Promise.all([killAndWait(harness.forwarder), killAndWait(harness.relay)]);
  await new Promise<void>((resolve) => harness.stub.close(() => resolve()));
  await rm(harness.tmpDir, { recursive: true, force: true });
}

// ---------------------------------------------------------------------------
// Real forwarder + relay + stub tests
// ---------------------------------------------------------------------------

describe.skipIf(process.platform === 'win32')('WK-0160: real forwarder+relay+stub end-to-end tunnel integration', () => {
  describe('request shape -- host, path, headers (d86240c class)', () => {
    let harness: TunnelHarness | undefined;
    let received: ReceivedRequest[] = [];

    beforeEach(async () => {
      received = [];
      harness = await startTunnelHarness({
        requestHandler: (req, res) => {
          received.push({ url: req.url, method: req.method, headers: req.headers });
          res.writeHead(200, { 'content-type': 'text/plain' });
          res.end('STUB_OK');
        },
      });
    });

    afterEach(async () => {
      if (harness) await stopTunnelHarness(harness);
      harness = undefined;
    });

    it(
      'an origin-form request through the relay reaches the stub with the operator-configured baseUrl path (/v1) preserved end-to-end',
      async () => {
        const h = harness!;
        // Calls the REAL buildPiBaseUrl (the d86240c fix) -- see header note.
        // It hardcodes TUNNEL_RELAY_PORT; substitute this harness's own
        // dynamically-allocated relay port so no fixed port is ever bound.
        const rawClientBaseUrl = buildPiBaseUrl(h.config.targetUrl);
        expect(rawClientBaseUrl).toBe(`http://127.0.0.1:${TUNNEL_RELAY_PORT}/v1`);
        const clientBaseUrl = rawClientBaseUrl.replace(`:${TUNNEL_RELAY_PORT}`, `:${h.relayPort}`);

        const status = await curlStatus(`${clientBaseUrl}/probe`);
        expect(status).toBe(200);

        expect(received).toHaveLength(1);
        expect(received[0].url).toBe('/v1/probe');
        // Host header rewritten to the REAL target's own host:port, not the
        // relay's loopback address the client actually connected to.
        expect(received[0].headers.host).toBe(`${h.stubHost}:${h.stubPort}`);
      },
      10_000,
    );

    it(
      'preserves a custom header end-to-end and strips proxy-connection (forwarder header handling)',
      async () => {
        const h = harness!;
        await new Promise<void>((resolve, reject) => {
          const req = httpRequest(
            {
              host: '127.0.0.1',
              port: h.relayPort,
              path: '/v1/headers-probe',
              method: 'GET',
              headers: { 'x-test-marker': 'abc123', 'proxy-connection': 'keep-alive' },
            },
            (res) => {
              res.resume();
              res.on('end', resolve);
            },
          );
          req.on('error', reject);
          req.end();
        });

        expect(received).toHaveLength(1);
        expect(received[0].headers['x-test-marker']).toBe('abc123');
        expect(received[0].headers['proxy-connection']).toBeUndefined();
      },
      10_000,
    );
  });

  describe('SSE/streaming passthrough (unbuffered)', () => {
    let harness: TunnelHarness | undefined;

    afterEach(async () => {
      if (harness) await stopTunnelHarness(harness);
      harness = undefined;
    });

    it(
      "relays streamed chunks progressively -- arrival gaps track the stub's own delays, proving nothing buffers the full response first",
      async () => {
        const CHUNK_DELAY_MS = 150;
        harness = await startTunnelHarness({
          requestHandler: (_req, res) => {
            res.writeHead(200, { 'content-type': 'text/event-stream' });
            res.write('data: chunk1\n\n');
            setTimeout(() => {
              res.write('data: chunk2\n\n');
              setTimeout(() => {
                res.write('data: chunk3\n\n');
                res.end();
              }, CHUNK_DELAY_MS);
            }, CHUNK_DELAY_MS);
          },
        });
        const h = harness;

        const chunkOffsets: number[] = [];
        const start = Date.now();
        await new Promise<void>((resolve, reject) => {
          const req = httpRequest({ host: '127.0.0.1', port: h.relayPort, path: '/v1/stream', method: 'GET' }, (res) => {
            res.on('data', () => chunkOffsets.push(Date.now() - start));
            res.on('end', resolve);
          });
          req.on('error', reject);
          req.end();
        });

        expect(chunkOffsets.length).toBeGreaterThanOrEqual(3);
        // Unbuffered: the gap between the FIRST and LAST chunk's arrival must
        // track the stub's own ~2x150ms inter-chunk delay. A buffering layer
        // anywhere in relay->socket->forwarder would collapse this gap to
        // near-zero (everything arriving in one burst at the very end).
        const gap = chunkOffsets[chunkOffsets.length - 1] - chunkOffsets[0];
        expect(gap).toBeGreaterThanOrEqual(CHUNK_DELAY_MS * 2 * 0.6); // generous CI-jitter tolerance
      },
      10_000,
    );
  });

  describe('allowlist enforcement over loopback (distinct alias 127.0.0.2 avoids same-IP false greens -- empirical finding, carried forward)', () => {
    let harness: TunnelHarness | undefined;
    let received: ReceivedRequest[] = [];

    beforeEach(async () => {
      received = [];
      harness = await startTunnelHarness({
        requestHandler: (req, res) => {
          received.push({ url: req.url, method: req.method, headers: req.headers });
          res.end('STUB_OK');
        },
      });
    });

    afterEach(async () => {
      if (harness) await stopTunnelHarness(harness);
      harness = undefined;
    });

    it(
      'denies an absolute-URI destination not on the allowlist (403) before ever dialing out',
      async () => {
        const h = harness!;
        // 127.0.0.3 is a THIRD, distinct loopback alias -- nothing listens
        // there. A fast 403 (not a hang/timeout) proves the forwarder denies
        // by an allowlist lookup alone, never attempting to connect out.
        const status = await curlStatus('http://127.0.0.3:9999/blocked', {
          extraArgs: ['-x', `http://127.0.0.1:${h.relayPort}`],
        });
        expect(status).toBe(403);
        expect(received).toHaveLength(0);
      },
      10_000,
    );

    it(
      'allows the granted destination through as an absolute-URI proxy request (200, real stub body reached)',
      async () => {
        const h = harness!;
        const status = await curlStatus(`http://${h.stubHost}:${h.stubPort}/v1/via-proxy`, {
          extraArgs: ['-x', `http://127.0.0.1:${h.relayPort}`],
        });
        expect(status).toBe(200);
        expect(received).toHaveLength(1);
        expect(received[0].url).toBe('/v1/via-proxy');
      },
      10_000,
    );
  });

  describe('no proxy-loop on loopback (19227fc class)', () => {
    let harness: TunnelHarness | undefined;
    let received: ReceivedRequest[] = [];
    let exportedEnv: Record<string, string> = {};

    beforeEach(async () => {
      received = [];
      harness = await startTunnelHarness({
        requestHandler: (req, res) => {
          received.push({ url: req.url, method: req.method, headers: req.headers });
          res.end('STUB_OK');
        },
      });
      // Derive the REAL proxy env values from tunnel.ts's own
      // buildTunnelBashLines() -- relayPort overridden to this harness's
      // dynamically-allocated port (no fixed TUNNEL_RELAY_PORT) -- rather
      // than hand-duplicating a literal. This is load-bearing: an earlier
      // version of this test hand-set the values itself and kept PASSING
      // even against a tunnel.ts with the no_proxy/NO_PROXY export lines
      // surgically removed (verified locally by reverse-applying 19227fc's
      // own diff and re-running this file — see the header's
      // red-verification note). Deriving from the real generated lines
      // closes that gap: if tunnel.ts stops exporting them, `exportedEnv`
      // below won't have them either.
      const bashLines = buildTunnelBashLines({ ...harness.config, relayPort: harness.relayPort }, harness.tmpDir);
      exportedEnv = extractShellExports(bashLines.preJailLines);
    });

    afterEach(async () => {
      if (harness) await stopTunnelHarness(harness);
      harness = undefined;
    });

    it(
      "WITHOUT no_proxy/NO_PROXY (only the HTTP_PROXY/http_proxy exports applied), a proxy-aware client (curl) self-referentially targets the relay's own address and is denied, never reaching the stub (the 19227fc bug, reproduced)",
      async () => {
        const h = harness!;
        const relayUrl = `http://127.0.0.1:${h.relayPort}`;
        expect(exportedEnv.HTTP_PROXY).toBe(relayUrl);
        // Directly captured while writing this file: with HTTP_PROXY set to
        // the SAME address as the request's own target and no_proxy/
        // NO_PROXY absent, curl sends an absolute-URI request line naming
        // the relay's own loopback address as the destination (not the real
        // target) -- the forwarder denies it (127.0.0.1 is not on the
        // allowlist; only the stub's real 127.0.0.2 is).
        const env: NodeJS.ProcessEnv = { ...process.env, HTTP_PROXY: exportedEnv.HTTP_PROXY, http_proxy: exportedEnv.http_proxy };
        delete env.NO_PROXY;
        delete env.no_proxy;

        const status = await curlStatus(`${relayUrl}/v1/looped`, { env });
        expect(status).toBe(403);
        expect(received).toHaveLength(0);
      },
      10_000,
    );

    it(
      'WITH the REAL no_proxy/NO_PROXY exports tunnel.ts generates (the 19227fc fix), the same client bypasses the proxy for the loopback target and reaches the stub directly (200)',
      async () => {
        const h = harness!;
        const relayUrl = `http://127.0.0.1:${h.relayPort}`;
        // Fails loud (before ever reaching curl) if tunnel.ts ever stops
        // exporting either casing.
        expect(exportedEnv.NO_PROXY).toBeDefined();
        expect(exportedEnv.no_proxy).toBeDefined();
        const env: NodeJS.ProcessEnv = {
          ...process.env,
          HTTP_PROXY: exportedEnv.HTTP_PROXY,
          http_proxy: exportedEnv.http_proxy,
          NO_PROXY: exportedEnv.NO_PROXY,
          no_proxy: exportedEnv.no_proxy,
        };

        const status = await curlStatus(`${relayUrl}/v1/direct`, { env });
        expect(status).toBe(200);
        expect(received).toHaveLength(1);
        expect(received[0].url).toBe('/v1/direct');
      },
      10_000,
    );
  });
});

// ---------------------------------------------------------------------------
// D8: env wiring -- runDispatch() -> real workerEnv (spawn mocked)
// ---------------------------------------------------------------------------

describe('WK-0160 D8: env wiring -- runDispatch() real workerEnv carries NO_PROXY/no_proxy (pipeline.ts:1018-1021)', () => {
  afterEach(() => {
    vi.restoreAllMocks();
  });

  /** A minimal, known-good fixture repo -- mirrors dispatch-v2-e2e.test.ts's setupS3Repo defaults (pi family, deepseek/openrouter, no credentials, web:false, mode:implement) so runDispatch() reaches spawnIsolated without any unrelated refusal gate tripping first. */
  async function setupEnvWiringRepo(): Promise<string> {
    const repoRoot = await createTempDir('kb-wk0160-envwiring-');
    execFileSync('git', ['init'], { cwd: repoRoot });
    execFileSync('git', ['config', 'user.email', 'test@example.com'], { cwd: repoRoot });
    execFileSync('git', ['config', 'user.name', 'Test User'], { cwd: repoRoot });

    const hoContent = `---
id: HO-WK0160-ENV
title: WK-0160 D8 env-wiring fixture
mode: implement
write_scope: ["src/"]
base_ref: null
web: false
credentials: []
data_mounts: []
read_first: []
vars: []
work_item: WK-9160
acceptance:
  - "AC-1: placeholder -- spawnIsolated is mocked, no worker actually runs"
validation: ["true"]
status: draft
---

## Task
Placeholder fixture for the WK-0160 D8 env-wiring test. spawnIsolated is
mocked below, so this body is never read by a real worker.
`;
    await mkdir(join(repoRoot, 'wiki', 'handoffs'), { recursive: true });
    await writeFile(join(repoRoot, 'wiki', 'handoffs', 'HO-WK0160-ENV.md'), hoContent, 'utf8');
    await writeFile(join(repoRoot, 'README.md'), 'kb-wk0160-envwiring-fixture\n', 'utf8');

    // WK-0116: mode=implement requires work_item to resolve to a real initiative.
    await mkdir(join(repoRoot, 'wiki', 'issues'), { recursive: true });
    await writeFile(
      join(repoRoot, 'wiki', 'issues', 'WK-9160.md'),
      '---\nid: "WK-9160"\ntitle: "Fixture WK"\nstatus: todo\ninitiative: IN-9160\n---\n\n# WK-9160: Fixture\n',
      'utf8',
    );
    await mkdir(join(repoRoot, 'wiki', 'initiatives'), { recursive: true });
    await writeFile(
      join(repoRoot, 'wiki', 'initiatives', 'IN-9160.md'),
      '---\nid: "IN-9160"\ntitle: "Fixture initiative"\nstatus: todo\n---\n\n# IN-9160: Fixture\n',
      'utf8',
    );

    await mkdir(join(repoRoot, 'wiki', '.dispatch'), { recursive: true });
    const models = { deepseek: { available_on: ['openrouter'], model_id: 'deepseek/deepseek-v4-flash-0731' } };
    const backends = {
      openrouter: { family: 'pi', base_url: 'https://openrouter.ai/api/v1', api_key_env: 'OPENROUTER_API_KEY', secrets_file: null },
    };
    const profiles = { schema_version: 1 };
    await writeFile(join(repoRoot, 'wiki', '.dispatch', 'models.json'), JSON.stringify(models, null, 2), 'utf8');
    await writeFile(join(repoRoot, 'wiki', '.dispatch', 'backends.json'), JSON.stringify(backends, null, 2), 'utf8');
    await writeFile(join(repoRoot, 'wiki', '.dispatch', 'profiles.json'), JSON.stringify(profiles, null, 2), 'utf8');

    execFileSync('git', ['add', '-A'], { cwd: repoRoot });
    execFileSync('git', ['commit', '-m', 'initial commit'], { cwd: repoRoot });

    // WK-0152: stamp base_sha = HEAD, then commit again (mirrors
    // dispatch-v2-e2e.test.ts's stampHandoff -- admission.ts's BASE_DRIFT
    // gate refuses a handoff with no valid base_sha).
    const head = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: repoRoot }).toString().trim();
    const hoPath = join(repoRoot, 'wiki', 'handoffs', 'HO-WK0160-ENV.md');
    const stamped = (await readFile(hoPath, 'utf8')).replace('base_ref: null\n', `base_ref: null\nbase_sha: "${head}"\n`);
    await writeFile(hoPath, stamped, 'utf8');
    execFileSync('git', ['add', '-A'], { cwd: repoRoot });
    execFileSync('git', ['commit', '-m', 'stamp'], { cwd: repoRoot });

    return repoRoot;
  }

  it('captures the real workerEnv the pipeline builds and asserts NO_PROXY/no_proxy = 127.0.0.1,localhost', async () => {
    const repoRoot = await setupEnvWiringRepo();
    let capturedEnv: Record<string, string> | undefined;
    vi.spyOn(spawnIsolatedModule, 'spawnIsolated').mockImplementation(async (plan, opts) => {
      capturedEnv = plan.env;
      if (opts?.stdoutLogPath) {
        await writeFile(opts.stdoutLogPath, readFixtureFile('pi-output-vllm-qwen25.jsonl'), 'utf8');
      }
      return {
        ok: true,
        data: { stdout: '', stderr: '', exitCode: 0, signal: null, truncated: false, timedOut: false, streamDrainTimedOut: false },
      };
    });

    try {
      const result = await runDispatch({
        dir: repoRoot,
        handoff: 'wiki/handoffs/HO-WK0160-ENV.md',
        model: 'deepseek',
        backend: 'openrouter',
        preflight: false,
      });
      expect(result.ok).toBe(true);
      if (!result.ok) return;

      expect(capturedEnv).toBeDefined();
      expect(capturedEnv!.NO_PROXY).toBe('127.0.0.1,localhost');
      expect(capturedEnv!.no_proxy).toBe('127.0.0.1,localhost');
      // The other half of the same wiring: the proxy address these two vars
      // exempt loopback FROM.
      expect(capturedEnv!.HTTP_PROXY).toBe(`http://127.0.0.1:${TUNNEL_RELAY_PORT}`);
      expect(capturedEnv!.https_proxy).toBe(`http://127.0.0.1:${TUNNEL_RELAY_PORT}`);
    } finally {
      await rm(repoRoot, { recursive: true, force: true });
    }
  });
});
